<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="smokeTest"
           tests="5"
           failures="1"
           errors="0"
           skipped="0"
           time="14.135">
  <properties />
            <testcase name="storeContect" time="0.062" classname="smoke.b.qccr.AccoutInfo_NormalTest">
                <failure type="java.lang.AssertionError"
                  message="门店联系方式信息不一致 expected [15111111665] but found [15111111665
0571-86044433]"
              >
<![CDATA[java.lang.AssertionError: 门店联系方式信息不一致 expected [15111111665] but found [15111111665
0571-86044433]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  com.common.ats.Assert.AtsAssertUtils.assertEquals(AtsAssertUtils.java:33)
  smoke.b.qccr.AccoutInfo_NormalTest.storeContect(AccoutInfo_NormalTest.java:50)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="yingYeOverTime" time="0.172" classname="smoke.b.qccr.AccoutInfo_NormalTest" />
                <testcase name="yingYeStatus" time="0.514" classname="smoke.b.qccr.AccoutInfo_NormalTest" />
                <testcase name="storeAddress" time="13.303" classname="smoke.b.qccr.AccoutInfo_NormalTest" />
                <testcase name="yingYeStartTime" time="0.084" classname="smoke.b.qccr.AccoutInfo_NormalTest" />
      
</testsuite>
